#!/bin/sh
set -e

if [ "$1" = configure ]; then
    update-mime-database /usr/share/mime >/dev/null 2>&1 || true
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
    /usr/share/gdm/generate-config >/dev/null 2>&1 || true
fi

#DEBHELPER#
exit 0
